# =============================================================================
# RAG Production System - Database Models
# =============================================================================
# 
# This module defines the database models for the RAG application.
# It contains the data structures that represent PDF documents,
# user queries, and their relationships in the database.
# 
# Author: [Your Name]
# Project: RAG Production System
# Version: 1.0.0
# 
# Models:
# - UploadedPDF: Stores information about uploaded PDF documents
# - Query: Records user questions and AI-generated responses
# =============================================================================

from django.db import models


class UploadedPDF(models.Model):
    """
    Database model for storing information about uploaded PDF documents.
    
    This model tracks PDF files that users upload to the system,
    storing metadata such as file location, upload timestamp, and
    user-provided names for easy identification and management.
    
    Attributes:
        file: The actual PDF file stored in the uploads directory
        uploaded_at: Automatic timestamp when the PDF was uploaded
        name: Optional user-provided name for the PDF document
    """
    
    # File field for storing the uploaded PDF document
    # upload_to='uploads/' creates a dedicated directory for PDF storage
    file = models.FileField(
        upload_to='uploads/',
        help_text="PDF file uploaded by the user for processing and analysis"
    )
    
    # Automatic timestamp field that records when the PDF was uploaded
    # auto_now_add=True ensures this is set only once during creation
    uploaded_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the PDF document was uploaded to the system"
    )
    
    # Optional character field for storing user-provided document names
    # blank=True allows empty values in forms, null=True allows database NULL values
    name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="User-provided name or title for the uploaded PDF document"
    )

    def __str__(self):
        """
        String representation of the UploadedPDF model.
        
        Returns:
            str: The PDF name if provided, otherwise a timestamp-based identifier
        """
        return self.name if self.name else f"PDF uploaded at {self.uploaded_at}"

    class Meta:
        """
        Meta options for the UploadedPDF model.
        
        This class provides additional configuration options for the model,
        including ordering, verbose names, and database table specifications.
        """
        # Order PDFs by upload time (newest first)
        ordering = ['-uploaded_at']
        # Human-readable name for the model in Django admin
        verbose_name = "Uploaded PDF Document"
        # Human-readable name for multiple instances
        verbose_name_plural = "Uploaded PDF Documents"


class Query(models.Model):
    """
    Database model for storing user queries and AI-generated responses.
    
    This model maintains a record of all questions asked by users
    and the corresponding responses generated by the RAG system.
    It establishes a relationship with uploaded PDFs to track
    which documents were used to answer specific questions.
    
    Attributes:
        user_query: The question or query submitted by the user
        response: The AI-generated answer based on PDF content
        created_at: Timestamp when the query was submitted
        pdf: Foreign key relationship to the associated PDF document
    """
    
    # Text field for storing the user's question or query
    # This field captures the complete question text for analysis
    user_query = models.TextField(
        help_text="The complete question or query submitted by the user"
    )
    
    # Text field for storing the AI-generated response
    # blank=True and null=True allow for delayed response generation
    response = models.TextField(
        blank=True,
        null=True,
        help_text="The intelligent response generated by the RAG system"
    )
    
    # Automatic timestamp field for tracking when queries are submitted
    # auto_now_add=True ensures this is set only once during creation
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the user query was submitted to the system"
    )
    
    # Foreign key relationship to the UploadedPDF model
    # This establishes a many-to-one relationship (many queries per PDF)
    # CASCADE deletion ensures queries are removed if the PDF is deleted
    pdf = models.ForeignKey(
        UploadedPDF,
        on_delete=models.CASCADE,
        related_name='queries',
        help_text="The PDF document that was used to generate the response"
    )

    def __str__(self):
        """
        String representation of the Query model.
        
        Returns:
            str: A descriptive string showing the PDF name and query timestamp
        """
        return f"Query on {self.pdf.name} at {self.created_at}"

    class Meta:
        """
        Meta options for the Query model.
        
        This class provides additional configuration options for the model,
        including ordering, verbose names, and database table specifications.
        """
        # Order queries by creation time (newest first)
        ordering = ['-created_at']
        # Human-readable name for the model in Django admin
        verbose_name = "User Query and Response"
        # Human-readable name for multiple instances
        verbose_name_plural = "User Queries and Responses"